# Generated by Django 5.1.6 on 2025-02-23 10:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_thumbnail', models.ImageField(upload_to='media/thum/')),
                ('video_title', models.CharField(max_length=100)),
                ('video_link', models.FileField(upload_to='media/video/')),
                ('video_description', models.CharField(max_length=5000)),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('video_aim', models.CharField(max_length=100)),
                ('cutomer_name', models.CharField(max_length=100)),
                ('view', models.FloatField(default=120.2)),
            ],
        ),
    ]
