# Generated by Django 5.1.6 on 2025-02-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videodetails',
            name='video_link',
            field=models.FileField(upload_to='video/'),
        ),
    ]
