# Generated by Django 5.1.6 on 2025-02-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_alter_videodetails_video_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videodetails',
            name='video_thumbnail',
            field=models.ImageField(upload_to='thum/'),
        ),
    ]
