# Generated by Django 5.1.6 on 2025-02-23 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_alter_videodetails_video_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videodetails',
            old_name='cutomer_name',
            new_name='customer_name',
        ),
    ]
