# Generated by Django 5.1.6 on 2025-03-01 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_rename_cutomer_name_videodetails_customer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vd_category', models.CharField(choices=[('comedy', 'comedy'), ('song', 'song'), ('other', 'other')], max_length=50)),
                ('vd_primary_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_primary', to='videos.videodetails')),
            ],
        ),
    ]
