# Generated by Django 5.1.6 on 2025-03-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_videocategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videodetails',
            name='video_title',
            field=models.CharField(max_length=200),
        ),
    ]
