# Generated by Django 5.1.6 on 2025-03-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_alter_videodetails_video_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocategory',
            name='vd_category',
            field=models.CharField(choices=[('comedy', 'comedy'), ('song', 'song'), ('movie', 'movie'), ('study', 'study'), ('games', 'games'), ('other activity', 'other activity')], max_length=50),
        ),
    ]
