# Generated by Django 5.1.6 on 2025-03-11 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_alter_videocategory_vd_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videodetails',
            name='video_description',
            field=models.TextField(max_length=5000),
        ),
    ]
