# Generated by Django 5.1.6 on 2025-03-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Profile_Image', models.ImageField(upload_to='profile/')),
                ('Name', models.CharField(max_length=100)),
                ('Channel_Name', models.CharField(max_length=100)),
                ('Title', models.CharField(max_length=100)),
            ],
        ),
    ]
