# Generated by Django 5.1.6 on 2025-03-10 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_name_profiledetails_namesuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiledetails',
            old_name='Title',
            new_name='uName',
        ),
    ]
