# Generated by Django 5.1.6 on 2025-03-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profiledetails_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledetails',
            name='Channel_Name',
            field=models.CharField(default='MediX User Profile', max_length=100),
        ),
        migrations.AlterField(
            model_name='profiledetails',
            name='Profile_Image',
            field=models.ImageField(default='media/profile/user_profile.jpg', max_length=2000, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='profiledetails',
            name='uName',
            field=models.CharField(default='yourmedix', max_length=100),
        ),
    ]
