# Generated by Django 5.1.6 on 2025-03-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_profiledetails_namesuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledetails',
            name='Profile_Image',
            field=models.ImageField(default='/profile/user_profile.jpg', max_length=2000, upload_to='profile/'),
        ),
    ]
