# Generated by Django 5.1.6 on 2025-03-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerdetails',
            name='contact_no',
            field=models.CharField(default='9820646838', max_length=10),
        ),
    ]
