# Generated by Django 5.1.6 on 2025-03-03 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0002_bannerdetails_contact_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerdetails',
            name='contact_no',
            field=models.CharField(max_length=10),
        ),
    ]
