# Generated by Django 5.1.6 on 2025-05-10 09:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0004_bannerdetails_uname'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerUploadUnSuccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_Images', models.ImageField(upload_to='BannerTime/')),
                ('banner_t', models.CharField(max_length=200)),
                ('banner_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('contact_no', models.CharField(max_length=15)),
                ('UserName', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
