# Generated by Django 5.1.6 on 2025-05-11 04:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0005_banneruploadunsuccess'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerTimeOver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BTO_Title', models.CharField(max_length=200)),
                ('BTO_Image', models.ImageField(upload_to='')),
                ('BTO_Contact', models.CharField(max_length=15)),
                ('BTO_Username', models.CharField(max_length=100)),
                ('BTO_Issue_Date', models.CharField(max_length=100)),
                ('BTO_End_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('BTO_Month', models.IntegerField(default=5)),
            ],
        ),
    ]
