# Generated by Django 5.1.6 on 2025-05-11 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0006_bannertimeover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannertimeover',
            name='BTO_Image',
            field=models.ImageField(upload_to='BannerOver/'),
        ),
    ]
