# Generated by Django 5.1.6 on 2025-05-11 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0007_alter_bannertimeover_bto_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannertimeover',
            name='BTO_Hr_Min_Sec',
            field=models.CharField(default='None', max_length=20),
        ),
    ]
