# Generated by Django 5.1.6 on 2025-02-25 19:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_thumbnail', models.ImageField(upload_to='thum/')),
                ('short_title', models.CharField(max_length=100)),
                ('short_link', models.FileField(upload_to='video/')),
                ('short_description', models.CharField(max_length=200)),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('customer_name', models.CharField(max_length=100)),
                ('view', models.FloatField(default=230.64)),
            ],
        ),
    ]
