# Generated by Django 5.1.6 on 2025-03-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0002_alter_shortsdetails_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortsdetails',
            name='short_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
