# Generated by Django 5.1.6 on 2025-03-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0003_alter_shortsdetails_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortsdetails',
            name='short_description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
