# Generated by Django 5.1.6 on 2025-03-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0005_alter_shortsdetails_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortsdetails',
            name='short_description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='shortsdetails',
            name='short_title',
            field=models.CharField(max_length=1000),
        ),
    ]
